<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-mateusozorioo/blob/main/atividade_praticas_em_numpy_mateusozorio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [ ]:
import numpy as np

array_zeros = np.zeros(10)

print(array_zeros)
print("Dtype:", array_zeros.dtype)
print("Shape:", array_zeros.shape)

### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [ ]:
import numpy as np

array_uns_float = np.ones(10, dtype=np.float64)

print(array_uns_float)
print(array_uns_float.dtype)
print(array_uns_float.shape)

### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [ ]:
import numpy as np

array_sequencia = np.arange(10)

print(array_sequencia)

### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [ ]:
import numpy as np

matriz_3x3 = np.arange(9).reshape(3, 3)

print(matriz_3x3)

### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [ ]:
import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])
indices_nao_zero = np.nonzero(v)

print(indices_nao_zero)

### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [ ]:
import numpy as np

vetor_linspace = np.linspace(0, 1, 12)

print(vetor_linspace)



```
# Isto está formatado como código
```

### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [ ]:
import numpy as np

identidade = np.eye(5)

print(identidade)

### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [ ]:
import numpy as np

rng = np.random.default_rng(42)

aleatorios = rng.random((3, 3, 3))

print(aleatorios)


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [ ]:
import numpy as np

matriz = np.random.random((10, 10))

print("Valor mínimo:", matriz.min())
print("Valor máximo:", matriz.max())


### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=float)

media = x.mean()
desvio = x.std()

x_normalizado = (x - media) / desvio
print(x_normalizado)


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.


In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
print("Tipo original:", a.dtype)

a_float = a.astype(np.float32)
print("Convertido para:", a_float.dtype)

a_int64 = a_float.astype(np.int64)
print("Convertido para:", a_int64.dtype)


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [ ]:
import numpy as np

a = np.array([2, 5, 7, 1, 9])

a_limitado = np.clip(a, 0, 5)
print(a_limitado)

### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

In [ ]:
import np as np

vetor = np.arange(10)
vetor_invertido = vetor[::-1]

print(vetor_invertido)

### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical = np.vstack((a, b))
print("Vertical:\n", vertical)

horizontal = np.hstack((a, b))
print("Horizontal:\n", horizontal)


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [ ]:
import numpy as np

matriz = np.diag([5, 5, 5, 5])
print(matriz)

### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print("Matriz A:\n", A)

soma_linhas = A.sum(axis=1)
print("Soma por linhas:", soma_linhas)

soma_colunas = A.sum(axis=0)
print("Soma por colunas:", soma_colunas)


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [ ]:
import numpy as np

rng = np.random.default_rng(42)
valores = rng.integers(0, 10, 100)

# Contando frequências
frequencias = np.bincount(valores, minlength=10)
print(frequencias)

### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [ ]:
import numpy as np

v = np.arange(20)
selecionado = v[1::3]
print(selecionado)

### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [ ]:
import numpy as np

v = np.arange(20)

mascara = (v % 2 == 0)
pares = v[mascara]

print("Máscara:", mascara)
print("Números pares:", pares)

### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.


In [ ]:
import numpy as np

lista = [[1, 2, 3], [4, 5, 6]]
array = np.array(lista)

print("Array:\n", array)
print("Shape:", array.shape)
print("Tipo de dados:", array.dtype)

### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

In [ ]:
import numpy as np

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)

### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [ ]:
A = np.array([[1.,2.,3.],[4.,5.,6.]])
A_centralizada = A - A.mean(axis=0)
print(A_centralizada)

### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

produto_elemento = a * b

produto_escalar = np.dot(a, b)

print("Elemento a elemento:", produto_elemento)
print("Produto escalar:", produto_escalar)

### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [ ]:
A = np.arange(12).reshape(3,4)
A[:, [0,2]] = A[:, [2,0]]
print(A)

### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [ ]:
A = np.array([[1,2],[3,4]])

flat = A.flatten()
ravel = A.ravel()

ravel[0] = 99

print("Original após alterar ravel:\n", A)
print("Flatten (cópia, não altera original):", flat)
print("Ravel (view, altera original):", ravel)

### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [ ]:
tabuleiro = np.zeros((8,8), dtype=int)
tabuleiro[1::2, ::2] = 1
tabuleiro[::2, 1::2] = 1
print(tabuleiro)

### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [ ]:
x = np.arange(-5, 6)
resultado = np.where(x < 0, 0, x)
print(resultado)

### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [ ]:
rng = np.random.default_rng(42)
valores = rng.random(1_000_000)

media = valores.mean()
erro = abs(media - 0.5)

print("Média:", media)
print("Erro absoluto:", erro)

### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [ ]:
a = np.array([1,2,3]).reshape(-1,1)
b = np.array([10,20,30,40])

somas = a + b
print(somas)

### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
import numpy as np

s = np.array([1, 2, 3, 4, 5])
k = np.array([2, 1])

janelas = sliding_window_view(s, k.shape[0])

resultado = np.sum(janelas * np.flip(k), axis=1)
print(resultado)

### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [ ]:
import numpy as np

rng = np.random.default_rng(42)
A = rng.normal(size=(5,4))
print("Original:\n", A)

min_col = A.min(axis=0)
max_col = A.max(axis=0)
range_col = max_col - min_col

range_col[range_col == 0] = 1

A_norm = (A - min_col) / range_col
print("\nNormalizado:\n", A_norm)


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.

In [ ]:
import numpy as np

A = np.array([[3,9],[1,4],[2,5]])

A_ordenado = A[A[:, 1].argsort()]
print(A_ordenado)

### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [5]:
import numpy as np

x = np.array([3,1,2,3,2,3,1])

valores, indices, contagens = np.unique(x, return_index=True, return_counts=True)

print("Valores únicos:", valores)
print("Primeira ocorrência:", indices)
print("Contagens:", contagens)

Valores únicos: [1 2 3]
Primeira ocorrência: [1 2 0]
Contagens: [2 2 3]


### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [3]:
import numpy as np

P = np.array([[0,0], [1,0], [0,1], [1,1]])  # exemplo com 4 pontos

diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]

D = np.sqrt(np.sum(diff**2, axis=-1))
print(D)

NameError: name 'np' is not defined

### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [2]:
import numpy as np

rng = np.random.default_rng(42)
X = rng.normal(size=(1000, 3))

cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)

print("Covariância:\n", cov)
print("\nCorrelação:\n", corr)

NameError: name 'np' is not defined

### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [6]:
import numpy as np

y = np.array([2, 0, 1, 2])
n_classes = y.max() + 1

one_hot = np.eye(n_classes)[y]
print(one_hot)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.


In [ ]:
import numpy as np

rng = np.random.default_rng(42)
X = rng.random((100, 2))

K = 3

centroides = X[rng.choice(len(X), K, replace=False)]

for it in range(10):

    distancias = np.linalg.norm(X[:, np.newaxis, :] - centroides[np.newaxis, :, :], axis=2)
    grupos = np.argmin(distancias, axis=1)

    novos_centroides = np.array([X[grupos == k].mean(axis=0) for k in range(K)])

    centroides = novos_centroides

print("Centróides finais:\n", centroides)


### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.


In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

X = rng.normal(size=(100, 2))
X[:, 1] = X[:, 0] * 0.8 + rng.normal(size=100) * 0.3
print("Shape dados X:", X.shape)

X_mean = X.mean(axis=0)
X_centered = X - X_mean

cov_matrix = np.cov(X_centered, rowvar=False)
print("\nMatriz Covariância (2x2):\n", cov_matrix)

autovalores, autovetores = np.linalg.eigh(cov_matrix)
print("\nAutovalores:", autovalores)
print("Autovetores:\n", autovetores)

indices_sort = np.argsort(autovalores)[::-1]
autovetores_sorted = autovetores[:, indices_sort]

W = autovetores_sorted[:, :1]
print("\n1º Componente Principal (W):\n", W)

Z = X_centered @ W
print("\nDados Projetados (Z) (100x1) (primeiros 5):", Z[:5].ravel())

X_reconstruido_centered = Z @ W.T

X_reconstruido = X_reconstruido_centered + X_mean
print("\nShape Reconstruído:", X_reconstruido.shape)

### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

I = np.arange(25).reshape(5, 5).astype(float)
K = np.array([[1, 0, -1],
              [1, 0, -1],
              [1, 0, -1]], dtype=float)

kH, kW = K.shape
iH, iW = I.shape

views = sliding_window_view(I, window_shape=(kH, kW))
print(f"Shape Imagem: {I.shape}")
print(f"Shape Kernel: {K.shape}")
print(f"Shape das Janelas (Views): {views.shape}")

K_flat = K.ravel()
print(f"Shape Kernel achatado: {K_flat.shape}")

views_flat = views.reshape(-1, kH * kW)
print(f"Shape Janelas achatadas: {views_flat.shape}")

conv_flat = views_flat @ K_flat

output_shape = (iH - kH + 1, iW - kW + 1)
conv_2d = conv_flat.reshape(output_shape)

print("\nConvolução 2D 'valid' (resultado):\n", conv_2d)

### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

N = 100

A = rng.random(size=(N, N)) + np.eye(N) * N
b = rng.random(size=N)

x = np.linalg.solve(A, b)

residuo = (A @ x) - b

norma_residuo = np.linalg.norm(residuo)
norma_b = np.linalg.norm(b)
residuo_relativo = norma_residuo / norma_b

cond_A = np.linalg.cond(A)

print(f"Sistema N={N}")
print(f"Número de Condição cond(A): {cond_A}")
print(f"Norma do Resíduo ||Ax - b||: {norma_residuo}")
print(f"Norma de b ||b||: {norma_b}")
print(f"Resíduo Relativo ||Ax - b|| / ||b||: {residuo_relativo}")

### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [ ]:
Python

import numpy as np

rng = np.random.default_rng(seed=42)

N, d = 100, 3
X = rng.random(size=(N, d))

beta_verdadeiro = np.array([5.0, -2.0, 1.5])
intercepto_verdadeiro = 3.0
ruido = rng.normal(scale=0.1, size=N)

y = intercepto_verdadeiro + (X @ beta_verdadeiro) + ruido

X_b = np.hstack([np.ones((N, 1)), X])
print(f"Shape X original: {X.shape}, Shape y: {y.shape}")
print(f"Shape X com intercepto (X_b): {X_b.shape}")

coefs, _, _, _ = np.linalg.lstsq(X_b, y, rcond=None)

intercepto_calc = coefs[0]
betas_calc = coefs[1:]

print("\n--- Resultados OLS ---")
print(f"Intercepto Verdadeiro (B0): {intercepto_verdadeiro:.4f}")
print(f"Intercepto Calculado: {intercepto_calc:.4f}")
print(f"\nBetas Verdadeiros (B1, B2, B3): {beta_verdadeiro}")
print(f"Betas Calculados: {betas_calc}")

y_pred = X_b @ coefs
mse = np.mean((y - y_pred)**2)
rmse = np.sqrt(mse)

print(f"\nRMSE (no treino): {rmse:.5f}")

### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.

In [ ]:

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

I = np.arange(36).reshape(6, 6)
print("Imagem Original (6x6):\n", I)

window_shape = (3, 3)

views = sliding_window_view(I, window_shape=window_shape)
print("\nShape das Views (Janelas):", views.shape)

media_local = views.mean(axis=(2, 3))

print("\nMatriz de Média Local 3x3 (4x4):\n", media_local)